// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlPackMan.Models;

namespace SqlPackMan.Migrations
{
    [DbContext(typeof(SqlPackManContext))]
    [Migration("20190316154638_newnew")]
    partial class newnew
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SqlPackMan.Models.DDSDatabase", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("DDSDatabase");
                });

            modelBuilder.Entity("SqlPackMan.Models.DdsEnvironment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Server");

                    b.Property<int>("SourceEnv");

                    b.Property<int>("TargetEnv");

                    b.HasKey("ID");

                    b.ToTable("DdsEnvironment");
                });

            modelBuilder.Entity("SqlPackMan.Models.Migration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DDSDatabaseId");

                    b.Property<DateTime>("EndTime");

                    b.Property<string>("MyProperty");

                    b.Property<string>("Name");

                    b.Property<string>("ResultText");

                    b.Property<string>("Source");

                    b.Property<DateTime>("StartTime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("ID");

                    b.HasIndex("DDSDatabaseId");

                    b.ToTable("Migration");
                });

            modelBuilder.Entity("SqlPackMan.Models.Package", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DdsEnvironmentId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(0);

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Description");

                    b.Property<int>("MaxEnvironment");

                    b.Property<string>("Name");

                    b.Property<string>("ScriptItems");

                    b.Property<string>("ScriptPost");

                    b.Property<string>("ScriptPre");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)");

                    b.Property<DateTime>("StatusDate");

                    b.Property<int>("StepNumber");

                    b.Property<string>("Version");

                    b.HasKey("ID");

                    b.HasIndex("DdsEnvironmentId");

                    b.ToTable("Package");
                });

            modelBuilder.Entity("SqlPackMan.Models.PackageItem", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DbObjectName");

                    b.Property<string>("DbObjectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)");

                    b.Property<int>("PackageId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(24)");

                    b.Property<int>("StepNumber");

                    b.HasKey("ID");

                    b.HasIndex("PackageId");

                    b.ToTable("PackageItem");
                });

            modelBuilder.Entity("SqlPackMan.Models.Migration", b =>
                {
                    b.HasOne("SqlPackMan.Models.DDSDatabase", "Database")
                        .WithMany()
                        .HasForeignKey("DDSDatabaseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SqlPackMan.Models.Package", b =>
                {
                    b.HasOne("SqlPackMan.Models.DdsEnvironment", "CurrentEnvironment")
                        .WithMany()
                        .HasForeignKey("DdsEnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SqlPackMan.Models.PackageItem", b =>
                {
                    b.HasOne("SqlPackMan.Models.Package")
                        .WithMany("Items")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
